### ISSUE TITLE
Create Multiple accounts at once

### ISSUE THREAD

**Issue by QuietKiller01** [davide-acanfora/spotify-account-generator#5]
Could you add that feature please?
Also can I save the credentials in a .txt?
Thanks in advance

**Comment by davide-acanfora** [comment]
Ok, I'll work on it

**Comment by QuietKiller01** [comment]
Thank you!!

**Comment by davide-acanfora** [comment]
Take a look at the latest update

**Comment by QuietKiller01** [comment]
Thanks for the quick update but I'm getting an error.
 "Could not load the page. Response code: 401"
What should I do?

**Comment by davide-acanfora** [comment]
Sorry, there was a typo in the code. Now it's fixed

**Comment by QuietKiller01** [comment]
Thank you!!

**Comment by QuietKiller01** [comment]
Now it says this:
C:\WINDOWS\system32hon spotify_generator.py
python: can't open file 'C:\WINDOWS\system32\spotify_generator.py': [Errno 2] No such file or directory
What should I do?

**Comment by QuietKiller01** [comment]
Now it says this:
C:\WINDOWS\system32>python spotify_generator.py
python: can't open file 'C:\WINDOWS\system32\spotify_generator.py': [Errno 2] No such file or directory
What should I do?

**Comment by BadMaliciousPyScripts** [comment]
You have to cd into the directory where the file is stored before executing the command.

**Comment by QuietKiller01** [comment]
How do I do that?
Sorry for the many questions I just don't know a lot about this stuff.

**Comment by BadMaliciousPyScripts** [comment]
I don't know where you have downloaded the file to but I for example have it on D:\Git\Spotify\AccountGen\
So I do:
cd /d D:\Git\Spotify\AccountGen\
(/d means that I change my drive e.g. from C to D)
python spotify_generator.py

**Comment by QuietKiller01** [comment]
Thank you but it still gives me errors without any explanation and doesn't do anything

**Comment by davide-acanfora** [comment]
Try it now, some fields were missing

**Comment by QuietKiller01** [comment]
Okay now everything works fine up until the generating when it says this:

Generating accounts in the following format:
NICKNAME:USERNAME:EMAIL:PASSWORD
Could not load the page. Response code: 429

And then does nothing

**Comment by BadMaliciousPyScripts** [comment]
Could not load the page. Response code: 429 Means too much requests where send from your IP address

**Comment by QuietKiller01** [comment]
How can I fix that?

**Comment by davide-acanfora** [comment]
There is no fix I can implement for that. Simply you are sending too many requests in a short period of time. That is a protection that services like Spotify adopt to block the use of this kind of scripts.

Since the functionality requested has been added and everything seems to be working, I'm closing this issue.

**Comment by QuietKiller01** [comment]
Okay sorry I was just able to figure out the correct way of doing it.
Thank you for your help and sorry for the inconvenience!
It is working now

**Comment by davide-acanfora** [comment]
No problem, feel free to open another issue if you need help
