### ISSUE TITLE
Could not create the account, some errors occurred

### ISSUE THREAD

**Issue by BadMaliciousPyScripts** [davide-acanfora/spotify-account-generator#6]
I am not using any proxy or VPN.
Python version: 3.9.4
requests version: 2.25.1

What is causing this?
I am not going to look into the code myself at least not today xD
If this isn't fixed tomorrow I will look at the code myself and see if I can fix it but it is 1 am and I can't even keep my eyes open.

**Comment by davide-acanfora** [comment]
Found the error, I forgot to add back some fields I had removed for testing. Let me know

**Comment by BadMaliciousPyScripts** [comment]
Works fine now thank you <3
