### ISSUE TITLE
Getting 403 now

### ISSUE THREAD

**Issue by petersolimine** [davide-acanfora/spotify-account-generator#7]
Such a cool tool! Thank you for sharing this publicly.

Seems like all requests are responding with 403 (forbidden) now. Is this because the provided key is expired in the request body?

Thx!

**Comment by davide-acanfora** [comment]
Thank you for reporting this issue!

I will give it a look as soon as possible.

**Comment by davide-acanfora** [comment]
I've just updated the script. No problem so far, let me know. Thanks!

**Comment by petersolimine** [comment]
Great! Thanks so much.
