### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Omkar-Mhatre** [davide-acanfora/spotify-account-generator#8]
It won't open it says "to find a version for your PC, contact owner publisher".

**Comment by MoJo-JoJo-exe** [comment]
I have created some fake accounts just to increase my followers. Eventually Spotify automatically deletes those accounts and I'm back to where I started. Is there any script to fix this or anything that automates fake account to make it look like a legit account.

**Comment by davide-acanfora** [comment]
> It won't open it says "to find a version for your PC, contact owner publisher".

This doesn't look like a Python error. Are you sure to have Python 3 installed? Then, make sure to follow the instructions in the README.


> I have created some fake accounts just to increase my followers. Eventually Spotify automatically deletes those accounts and I'm back to where I started. Is there any script to fix this or anything that automates fake account to make it look like a legit account.

Any decent system will detect a strange behaviour like the sudden increase in followers. Spotify for sure is one of them. Even if I make the accounts look like legit accounts (e.g. real names or emails), it all boils down to avoiding sudden increases in followers. Nonetheless, even if you managed to spread followers over time, they will likely still be banned as they have no other activities
